// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, depend_on_referenced_packages
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'get yours from console',
    appId: 'get yours from console',
    messagingSenderId: 'get yours from console',
    projectId: 'get yours from console',
    authDomain: 'test.firebaseapp.com',
    databaseURL: 'https://test.firebaseio.com',
    storageBucket: 'test.appspot.com',
    measurementId: 'get yours from console',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'get yours from console',
    appId: 'get yours from console',
    messagingSenderId: 'get yours from console',
    projectId: 'get yours from console',
    databaseURL: 'https://test.firebaseio.com',
    storageBucket: 'test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'get yours from console',
    appId: 'get yours from console',
    messagingSenderId: 'get yours from console',
    projectId: 'get yours from console',
    authDomain: 'test.firebaseapp.com',
    databaseURL: 'https://test.firebaseio.com',
    storageBucket: 'test.appspot.com',
    measurementId: 'get yours from console',
    androidClientId: 'test.apps.googleusercontent.com',
    iosClientId: 'test.apps.googleusercontent.com',
    iosBundleId: 'com.waheduzzaman.open.weather.app.openSkyWeather',
  );
}
